routes:
  /tintinnabuli/:
    controller: channel
    filter: tag:[superorganismen,komplexitet]
    template: collections
  /noveller/:
    controller: channel
    filter: tag:[flickan-vid-pianot,dikter]
    template: noveller


collections:
  /:
    permalink: /{slug}/
    template: index
#    filter: tag:-[tag/no-more-issues,tag/books]
    /superorganismen/:
      permalink: /tag/superorganismen/{slug}/
      filter: tag:supersorganismen
      template: index
    /komplexitet/:
      permalink: /tag/komplexitet/{slug}/
      filter: tag:komplexitet
      template: index
    /flickan-vid-pianot/:
      permalink: /tag/flickan-vid-pianot/{slug}/
      filter: tag:flickan-vid-pianot
      template: index
    /dikter/:
      permalink: /tag/dikter/{slug}/
      filter: tag:dikter
      template: index
#    /tag/: 
#      permalink: /tag/{slug}/
#      filter: 'tag:-books+tag:-no-more-issues'


taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
