routes:
  /tintinnabuli/:
    controller: channel
    filter: tag:[superorganismen,komplexitet]
    template: collections


collections:
  /:
    permalink: /{slug}/
    template: index
#    filter: tag:-[tag/no-more-issues,tag/books]
    /superorganismen/:
      permalink: /tag/superorganismen/{slug}/
      filter: tag:supersorganismen
      template: index
    /komplexitet/:
      permalink: /tag/komplexitet/{slug}/
      filter: tag:komplexitet
      template: index
#    /tag/: 
#      permalink: /tag/{slug}/
#      filter: 'tag:-books+tag:-no-more-issues'


taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
